name: Release

on:
  release:
    types:
      - created

jobs:
  Example:
    name: Example
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Ahk2Exe
        uses: nekocodeX/GitHub-Action-Ahk2Exe@main
        with:
          in: swap.ahk
      

        